// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
 import 'firebase_options.dart';


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQUiyCjqxwza5qWfnJ-e7UJuh7v3PIOLk',
    appId: '1:784592357227:web:ce68e9e3d858ba2c18ae2e',
    messagingSenderId: '784592357227',
    projectId: 'signin-822fe',
    authDomain: 'signin-822fe.firebaseapp.com',
    storageBucket: 'signin-822fe.appspot.com',
    measurementId: 'G-FG6CQVKNBP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBa4m1w5QduhwPd04wNgHAWV5vIbFzuQgQ',
    appId: '1:784592357227:android:176a06f17ea605ee18ae2e',
    messagingSenderId: '784592357227',
    projectId: 'signin-822fe',
    storageBucket: 'signin-822fe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfPZoU4W8ZbXoDYasDnyj4jWJNZWOfPQE',
    appId: '1:784592357227:ios:58e1432b422a48a718ae2e',
    messagingSenderId: '784592357227',
    projectId: 'signin-822fe',
    storageBucket: 'signin-822fe.appspot.com',
    androidClientId: '784592357227-g9ecggi6kab33quqj5s0cr4l63v981ma.apps.googleusercontent.com',
    iosClientId: '784592357227-6g5hd9ch2ed1gs3ug91rktjbifnjhjnp.apps.googleusercontent.com',
    iosBundleId: 'com.example.helloworld',
  );
}
